name: CI Pipeline
run-name: CI Pipeline of ${{ github.ref_name }}

on:
  push:
    branches:
      - "**"

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'
          cache: 'maven'

      - name: Run test
        run: mvn clean test
